version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
    - data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8000:8081
    depends_on:
      - mongo

  java-app:
    image: group-java-app
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: prod_db
    depends_on:
      - mongo